"""Regenerate `benchmarks/baselines/vendor/agentless_fl.py` from Agentless.

Downloads the pinned Agentless commit and copies the exact source text
(`ast.get_source_segment`) of every function, class and prompt the
localization baseline uses into one module - nothing is re-typed, so the
vendored code stays verifiable against upstream:

    python scripts/vendor_agentless.py

Agentless: https://github.com/OpenAutoCoder/Agentless (MIT License,
Copyright (c) 2024 OpenAutoCoder).
"""
from __future__ import annotations

import ast
import urllib.request
from pathlib import Path

COMMIT = "5ce5888b9f149beaace393957a55ea8ee46c9f71"
RAW = f"https://raw.githubusercontent.com/OpenAutoCoder/Agentless/{COMMIT}/"
OUT = Path(__file__).resolve().parent.parent / "benchmarks/baselines/vendor/agentless_fl.py"

#: upstream file -> top-level names copied verbatim, in order
PIECES = {
    "get_repo_structure/get_repo_structure.py": ["parse_python_file", "create_structure"],
    "agentless/util/compress_file.py": [
        "CompressTransformer", "GlobalVariableVisitor", "remove_lines", "compress_assign_stmts", "get_skeleton",
    ],
    "agentless/util/preprocess_data.py": [
        "show_project_structure", "filter_out_test_files", "filter_none_python",
        "get_full_file_paths_and_classes_and_functions", "get_repo_files", "correct_file_paths",
    ],
    "agentless/util/postprocess_data.py": ["extract_code_blocks", "extract_locs_for_files"],
}
#: `LLMFL` class attributes copied verbatim from agentless/fl/FL.py
FL_ATTRS = [
    "obtain_relevant_files_prompt",
    "file_content_in_block_template",
    "obtain_relevant_functions_and_vars_from_compressed_files_prompt_more",
]


def fetch(path: str) -> str:
    with urllib.request.urlopen(RAW + path, timeout=30) as resp:
        return resp.read().decode("utf-8")


def segment(source: str, name: str) -> str:
    tree = ast.parse(source)
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and node.name == name:
            return ast.get_source_segment(source, node, padded=True)
    raise KeyError(f"{name} not found upstream")


def fl_attrs(source: str) -> list[str]:
    tree = ast.parse(source)
    cls = next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == "LLMFL")
    out = []
    for name in FL_ATTRS:
        node = next(n for n in cls.body if isinstance(n, ast.Assign) and n.targets[0].id == name)
        seg = ast.get_source_segment(source, node)
        out.append(seg)
    max_tokens = next(
        n for n in ast.walk(cls) if isinstance(n, ast.Assign) and isinstance(n.targets[0], ast.Attribute)
        and n.targets[0].attr == "max_tokens"
    )
    out.append(f"MAX_TOKENS = {ast.get_source_segment(source, max_tokens.value)}  # LLMFL.__init__: self.max_tokens")
    return out


def main() -> None:
    parts = [
        '"""Verbatim excerpts of Agentless (fault localization stages).',
        "",
        f"Source: https://github.com/OpenAutoCoder/Agentless @ {COMMIT}",
        "Generated by scripts/vendor_agentless.py - do not edit by hand.",
        "",
        "MIT License. Copyright (c) 2024 OpenAutoCoder. Permission is hereby granted,",
        "free of charge, to any person obtaining a copy of this software and",
        "associated documentation files, to deal in the Software without",
        "restriction, subject to including this notice. THE SOFTWARE IS PROVIDED",
        '"AS IS", WITHOUT WARRANTY OF ANY KIND."""',
        "# ruff: noqa",
        "# mypy: ignore-errors",
        "import ast",
        "import os",
        "import re",
        "",
        "import libcst as cst",
        "import libcst.matchers as m",
        "",
    ]
    for path, names in PIECES.items():
        src = fetch(path)
        parts.append(f"\n# ---- {path} " + "-" * max(0, 60 - len(path)))
        for name in names:
            parts.append(segment(src, name))
            parts.append("")
    fl = fetch("agentless/fl/FL.py")
    parts.append("\n# ---- agentless/fl/FL.py (LLMFL prompt templates) " + "-" * 12)
    for seg in fl_attrs(fl):
        parts.append(seg.strip())
        parts.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    (OUT.parent / "__init__.py").write_text('"""Vendored third-party code (see each module\'s header)."""\n')
    OUT.write_text("\n".join(parts).rstrip() + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
