"""v1.1+: the complete, curated canonical sink taxonomy - every concrete
qualified callable, driver constructor, or runtime boundary this codebase
recognizes across Python, JavaScript/TypeScript, and Go, across all 6
`Substance` I/O categories.

This is the literal registry the engineering spec asked for, transcribed
verbatim with one deliberate correction: the spec's own Go entries for
`github.com/...` and `go-redis`-style import paths were pasted through a
markdown auto-linkifier (`"[github.com/jackc/pgx.Connect](https://github.com/jackc/pgx.Connect)"`
instead of the plain string `"github.com/jackc/pgx.Connect"`) - every such
entry below is the plain qualified-path string the surrounding matching
logic (`prism.semantics.substance`) actually expects, not the corrupted
markdown-link form, which would never match anything.

Previously inlined directly in `prism.semantics.substance`; split into its
own module purely so the taxonomy itself - now large enough to need its
own home - can be read, diffed, and extended independently of the
matching logic that consumes it.
"""
from __future__ import annotations

CANONICAL_SINKS: dict[str, dict[str, set[str]]] = {
    "network_io": {
        "python": {
            # requests
            "requests.request",
            "requests.get",
            "requests.post",
            "requests.put",
            "requests.patch",
            "requests.delete",
            "requests.head",
            "requests.options",
            # httpx
            "httpx.request",
            "httpx.get",
            "httpx.post",
            "httpx.put",
            "httpx.patch",
            "httpx.delete",
            "httpx.head",
            "httpx.options",
            "httpx.Client",
            "httpx.AsyncClient",
            "httpx.Client.request",
            "httpx.AsyncClient.request",
            # urllib
            "urllib.request.urlopen",
            "urllib.request.Request",
            # urllib3
            "urllib3.PoolManager.request",
            "urllib3.PoolManager.urlopen",
            "urllib3.request",
            # stdlib HTTP
            "http.client.HTTPConnection",
            "http.client.HTTPSConnection",
            "http.client.HTTPConnection.request",
            "http.client.HTTPConnection.send",
            "http.client.HTTPSConnection.request",
            # aiohttp
            "aiohttp.request",
            "aiohttp.ClientSession",
            "aiohttp.ClientSession.request",
            "aiohttp.ClientSession.get",
            "aiohttp.ClientSession.post",
            "aiohttp.ClientSession.put",
            "aiohttp.ClientSession.patch",
            "aiohttp.ClientSession.delete",
            "aiohttp.ClientSession.head",
            # sockets
            "socket.socket",
            "socket.create_connection",
            "socket.create_server",
            "socket.socket.connect",
            "socket.socket.connect_ex",
            "socket.socket.send",
            "socket.socket.sendall",
            "socket.socket.recv",
            "socket.socket.recvfrom",
            "socket.socket.accept",
            # TLS
            "ssl.wrap_socket",
            "ssl.SSLContext.wrap_socket",
            "ssl.SSLContext.wrap_bio",
            # WebSocket
            "websocket.create_connection",
            "websocket.WebSocket.connect",
            "websockets.connect",
            # FTP / SMTP / IMAP / POP
            "ftplib.FTP",
            "ftplib.FTP.connect",
            "ftplib.FTP.login",
            "ftplib.FTP.storbinary",
            "ftplib.FTP.storlines",
            "ftplib.FTP.retrbinary",
            "ftplib.FTP.retrlines",
            "smtplib.SMTP",
            "smtplib.SMTP_SSL",
            "smtplib.SMTP.connect",
            "smtplib.SMTP.sendmail",
            "smtplib.SMTP.send_message",
            "imaplib.IMAP4",
            "imaplib.IMAP4_SSL",
            "imaplib.IMAP4.login",
            "imaplib.IMAP4.select",
            "imaplib.IMAP4.search",
            "imaplib.IMAP4.fetch",
            "poplib.POP3",
            "poplib.POP3_SSL",
            "poplib.POP3.user",
            "poplib.POP3.pass_",
            # RPC / SDKs
            "grpc.insecure_channel",
            "grpc.secure_channel",
            "grpc.aio.insecure_channel",
            "grpc.aio.secure_channel",
            "boto3.client",
            "boto3.resource",
        },
        "javascript": {
            # Fetch
            "fetch",
            "globalThis.fetch",
            "window.fetch",
            # axios
            "axios",
            "axios.request",
            "axios.get",
            "axios.post",
            "axios.put",
            "axios.patch",
            "axios.delete",
            "axios.head",
            "axios.options",
            # Node HTTP
            "http.request",
            "http.get",
            "https.request",
            "https.get",
            # undici
            "undici.request",
            "undici.fetch",
            "undici.stream",
            "undici.pipeline",
            # node-fetch
            "node-fetch",
            "node-fetch.default",
            # got
            "got",
            "got.get",
            "got.post",
            "got.put",
            "got.patch",
            "got.delete",
            # raw networking
            "net.createConnection",
            "net.connect",
            "net.createServer",
            "tls.connect",
            "tls.createServer",
            "dgram.createSocket",
            # DNS
            "dns.lookup",
            "dns.resolve",
            "dns.resolve4",
            "dns.resolve6",
            "dns.resolveMx",
            "dns.resolveTxt",
            "dns.resolveSrv",
            # WebSocket
            "WebSocket",
            "ws",
            "ws.WebSocket",
        },
        "go": {
            # HTTP client
            "net/http.Get",
            "net/http.Head",
            "net/http.Post",
            "net/http.PostForm",
            "net/http.NewRequest",
            "net/http.NewRequestWithContext",
            "net/http.Client.Do",
            "net/http.Client.Get",
            "net/http.Client.Head",
            "net/http.Client.Post",
            "net/http.Client.PostForm",
            "net/http.Transport.RoundTrip",
            # Raw networking
            "net.Dial",
            "net.DialTimeout",
            "net.DialTCP",
            "net.DialUDP",
            "net.Listen",
            "net.ListenTCP",
            "net.ListenUDP",
            "net.ListenPacket",
            "net.ResolveIPAddr",
            "net.ResolveTCPAddr",
            "net.ResolveUDPAddr",
            # TLS
            "crypto/tls.Dial",
            "crypto/tls.DialWithDialer",
            "crypto/tls.Listen",
            "crypto/tls.Server",
            # RPC
            "google.golang.org/grpc.Dial",
            "google.golang.org/grpc.DialContext",
            "google.golang.org/grpc.NewServer",
        },
    },
    "database_io": {
        "python": {
            # sqlite3
            "sqlite3.connect",
            "sqlite3.Connection.execute",
            "sqlite3.Connection.executemany",
            "sqlite3.Connection.executescript",
            "sqlite3.Connection.commit",
            "sqlite3.Connection.rollback",
            "sqlite3.Cursor.execute",
            "sqlite3.Cursor.executemany",
            "sqlite3.Cursor.executescript",
            # psycopg / psycopg2
            "psycopg.connect",
            "psycopg.AsyncConnection.connect",
            "psycopg.Connection.execute",
            "psycopg.Cursor.execute",
            "psycopg2.connect",
            "psycopg2.extensions.connection.cursor",
            # SQLAlchemy
            "sqlalchemy.create_engine",
            "sqlalchemy.engine.Connection.execute",
            "sqlalchemy.engine.Connection.exec_driver_sql",
            "sqlalchemy.orm.Session.execute",
            "sqlalchemy.orm.Session.commit",
            "sqlalchemy.orm.Session.rollback",
            "sqlalchemy.orm.Session.add",
            "sqlalchemy.orm.Session.delete",
            # Django ORM
            "django.db.connection.cursor",
            "django.db.backends.base.base.BaseDatabaseWrapper.cursor",
            "django.db.models.QuerySet.create",
            "django.db.models.QuerySet.update",
            "django.db.models.QuerySet.delete",
            "django.db.models.Manager.create",
            # PyMongo
            "pymongo.MongoClient",
            "pymongo.collection.Collection.insert_one",
            "pymongo.collection.Collection.insert_many",
            "pymongo.collection.Collection.update_one",
            "pymongo.collection.Collection.update_many",
            "pymongo.collection.Collection.delete_one",
            "pymongo.collection.Collection.delete_many",
            "pymongo.collection.Collection.find",
            "pymongo.collection.Collection.find_one",
            # Redis
            "redis.Redis",
            "redis.Redis.get",
            "redis.Redis.set",
            "redis.Redis.delete",
            "redis.Redis.execute_command",
            "redis.Redis.hget",
            "redis.Redis.hset",
            "redis.Redis.lpush",
            "redis.Redis.rpush",
            "redis.Redis.sadd",
            "redis.Redis.srem",
            "redis.Redis.expire",
            # MySQL
            "pymysql.connect",
            "mysql.connector.connect",
            "mysql.connector.connection.MySQLConnection.cursor",
            "mysql.connector.cursor.MySQLCursor.execute",
            # Other drivers
            "asyncpg.connect",
            "asyncpg.create_pool",
            "pyodbc.connect",
            "oracledb.connect",
            "cx_Oracle.connect",
        },
        "javascript": {
            # pg
            "pg.Client",
            "pg.Pool",
            "pg.Client.query",
            "pg.Pool.query",
            "pg.Pool.connect",
            # mysql / mysql2
            "mysql.createConnection",
            "mysql.createPool",
            "mysql2.createConnection",
            "mysql2.createPool",
            "mysql2/promise.createConnection",
            "mysql2/promise.createPool",
            # SQLite
            "sqlite3.Database",
            "sqlite3.Database.run",
            "sqlite3.Database.exec",
            "sqlite3.Database.get",
            "sqlite3.Database.all",
            "better-sqlite3",
            "better-sqlite3.Database",
            "better-sqlite3.Database.prepare",
            # Mongo
            "mongodb.MongoClient",
            "mongodb.Db.collection",
            "mongodb.Collection.insertOne",
            "mongodb.Collection.insertMany",
            "mongodb.Collection.updateOne",
            "mongodb.Collection.updateMany",
            "mongodb.Collection.deleteOne",
            "mongodb.Collection.deleteMany",
            "mongodb.Collection.find",
            "mongodb.Collection.findOne",
            # Mongoose
            "mongoose.connect",
            "mongoose.Model.create",
            "mongoose.Model.find",
            "mongoose.Model.findOne",
            "mongoose.Model.updateOne",
            "mongoose.Model.updateMany",
            "mongoose.Model.deleteOne",
            "mongoose.Model.deleteMany",
            "mongoose.Document.save",
            # ORM / query builders
            "sequelize",
            "sequelize.Sequelize",
            "sequelize.Model.create",
            "sequelize.Model.update",
            "sequelize.Model.destroy",
            "sequelize.Model.findAll",
            "sequelize.Model.findOne",
            "prisma.PrismaClient",
            "prisma.PrismaClient.$queryRaw",
            "prisma.PrismaClient.$executeRaw",
            "knex",
            "knex.raw",
            # Redis
            "redis.createClient",
            "redis.RedisClient",
            "ioredis",
            "ioredis.Redis",
            "ioredis.Redis.get",
            "ioredis.Redis.set",
            "ioredis.Redis.del",
            "ioredis.Redis.hset",
            "ioredis.Redis.lpush",
            "ioredis.Redis.rpush",
        },
        "go": {
            # database/sql
            "database/sql.Open",
            "database/sql.OpenDB",
            "database/sql.DB.Exec",
            "database/sql.DB.ExecContext",
            "database/sql.DB.Query",
            "database/sql.DB.QueryContext",
            "database/sql.DB.QueryRow",
            "database/sql.DB.QueryRowContext",
            "database/sql.DB.Begin",
            "database/sql.DB.BeginTx",
            "database/sql.DB.Ping",
            "database/sql.DB.PingContext",
            "database/sql.DB.Prepare",
            "database/sql.DB.PrepareContext",
            # transactions
            "database/sql.Tx.Exec",
            "database/sql.Tx.ExecContext",
            "database/sql.Tx.Query",
            "database/sql.Tx.QueryContext",
            "database/sql.Tx.QueryRow",
            "database/sql.Tx.QueryRowContext",
            "database/sql.Tx.Commit",
            "database/sql.Tx.Rollback",
            # PostgreSQL
            "github.com/jackc/pgx.Connect",
            "github.com/jackc/pgx.ConnectConfig",
            "github.com/jackc/pgx.Conn.Exec",
            "github.com/jackc/pgx.Conn.Query",
            "github.com/jackc/pgx.Conn.QueryRow",
            # MongoDB
            "go.mongodb.org/mongo-driver/mongo.Connect",
            "go.mongodb.org/mongo-driver/mongo.Client.Database",
            "go.mongodb.org/mongo-driver/mongo.Collection.InsertOne",
            "go.mongodb.org/mongo-driver/mongo.Collection.InsertMany",
            "go.mongodb.org/mongo-driver/mongo.Collection.UpdateOne",
            "go.mongodb.org/mongo-driver/mongo.Collection.UpdateMany",
            "go.mongodb.org/mongo-driver/mongo.Collection.DeleteOne",
            "go.mongodb.org/mongo-driver/mongo.Collection.DeleteMany",
            "go.mongodb.org/mongo-driver/mongo.Collection.Find",
            "go.mongodb.org/mongo-driver/mongo.Collection.FindOne",
            # Redis
            "github.com/redis/go-redis/v9.NewClient",
            "github.com/redis/go-redis/v9.Client.Get",
            "github.com/redis/go-redis/v9.Client.Set",
            "github.com/redis/go-redis/v9.Client.Del",
            "github.com/redis/go-redis/v9.Client.HSet",
            "github.com/redis/go-redis/v9.Client.LPush",
            "github.com/redis/go-redis/v9.Client.RPush",
            # GORM
            "gorm.io/gorm.Open",
            "gorm.io/gorm.DB.Create",
            "gorm.io/gorm.DB.Save",
            "gorm.io/gorm.DB.Delete",
            "gorm.io/gorm.DB.Updates",
            "gorm.io/gorm.DB.Find",
            "gorm.io/gorm.DB.First",
            "gorm.io/gorm.DB.Raw",
            "gorm.io/gorm.DB.Exec",
        },
    },
    "filesystem_io": {
        "python": {
            # Built-in open
            "builtins.open",
            "open",
            # os
            "os.open",
            "os.close",
            "os.read",
            "os.readv",
            "os.write",
            "os.writev",
            "os.pread",
            "os.pwrite",
            "os.rename",
            "os.replace",
            "os.remove",
            "os.unlink",
            "os.mkdir",
            "os.makedirs",
            "os.rmdir",
            "os.listdir",
            "os.scandir",
            "os.stat",
            "os.lstat",
            "os.chmod",
            "os.chown",
            "os.link",
            "os.symlink",
            "os.truncate",
            # pathlib
            "pathlib.Path.open",
            "pathlib.Path.read_text",
            "pathlib.Path.write_text",
            "pathlib.Path.read_bytes",
            "pathlib.Path.write_bytes",
            "pathlib.Path.unlink",
            "pathlib.Path.rename",
            "pathlib.Path.replace",
            "pathlib.Path.mkdir",
            "pathlib.Path.rmdir",
            "pathlib.Path.touch",
            "pathlib.Path.chmod",
            "pathlib.Path.symlink_to",
            "pathlib.Path.hardlink_to",
            # shutil
            "shutil.copy",
            "shutil.copy2",
            "shutil.copyfile",
            "shutil.copytree",
            "shutil.move",
            "shutil.rmtree",
            # tempfile
            "tempfile.TemporaryFile",
            "tempfile.NamedTemporaryFile",
            "tempfile.SpooledTemporaryFile",
            "tempfile.TemporaryDirectory",
            "tempfile.mkstemp",
            "tempfile.mkdtemp",
            # archive writers
            "zipfile.ZipFile",
            "zipfile.ZipFile.write",
            "zipfile.ZipFile.writestr",
            "tarfile.open",
            "tarfile.TarFile.add",
            "tarfile.TarFile.extract",
            "tarfile.TarFile.extractall",
            # mmap
            "mmap.mmap",
        },
        "javascript": {
            # fs
            "fs.open",
            "fs.openSync",
            "fs.close",
            "fs.closeSync",
            "fs.read",
            "fs.readSync",
            "fs.write",
            "fs.writeSync",
            "fs.readFile",
            "fs.readFileSync",
            "fs.writeFile",
            "fs.writeFileSync",
            "fs.appendFile",
            "fs.appendFileSync",
            "fs.rename",
            "fs.renameSync",
            "fs.unlink",
            "fs.unlinkSync",
            "fs.rm",
            "fs.rmSync",
            "fs.mkdir",
            "fs.mkdirSync",
            "fs.rmdir",
            "fs.rmdirSync",
            "fs.readdir",
            "fs.readdirSync",
            "fs.stat",
            "fs.statSync",
            "fs.lstat",
            "fs.lstatSync",
            "fs.copyFile",
            "fs.copyFileSync",
            "fs.cp",
            "fs.cpSync",
            "fs.truncate",
            "fs.truncateSync",
            "fs.watch",
            # promises
            "fs.promises.open",
            "fs.promises.readFile",
            "fs.promises.writeFile",
            "fs.promises.appendFile",
            "fs.promises.rename",
            "fs.promises.unlink",
            "fs.promises.rm",
            "fs.promises.mkdir",
            "fs.promises.readdir",
            "fs.promises.stat",
            "fs.promises.lstat",
            "fs.promises.copyFile",
            "fs.promises.cp",
            "fs.promises.truncate",
        },
        "go": {
            # os
            "os.Open",
            "os.OpenFile",
            "os.Create",
            "os.ReadFile",
            "os.WriteFile",
            "os.Remove",
            "os.RemoveAll",
            "os.Rename",
            "os.Mkdir",
            "os.MkdirAll",
            "os.ReadDir",
            "os.Stat",
            "os.Lstat",
            "os.Chmod",
            "os.Chown",
            "os.Link",
            "os.Symlink",
            "os.Truncate",
            # File methods
            "os.File.Read",
            "os.File.ReadAt",
            "os.File.ReadFrom",
            "os.File.Write",
            "os.File.WriteAt",
            "os.File.WriteString",
            "os.File.Seek",
            "os.File.Truncate",
            "os.File.Sync",
            "os.File.Close",
            # io
            "io.ReadAll",
            "io.Copy",
            "io.CopyN",
            "io.CopyBuffer",
            "io.WriteString",
            # ioutil
            "io/ioutil.ReadFile",
            "io/ioutil.WriteFile",
            "io/ioutil.TempFile",
            "io/ioutil.TempDir",
            # filepath operations touching FS
            "path/filepath.Walk",
            "path/filepath.WalkDir",
            # archives
            "archive/zip.Writer.Create",
            "archive/zip.Writer.CreateHeader",
            "archive/tar.Writer.Write",
            "archive/tar.Writer.WriteHeader",
        },
    },
    "process_io": {
        "python": {
            "subprocess.run",
            "subprocess.call",
            "subprocess.check_call",
            "subprocess.check_output",
            "subprocess.Popen",
            "os.system",
            "os.popen",
            "os.spawnl",
            "os.spawnle",
            "os.spawnlp",
            "os.spawnlpe",
            "os.spawnv",
            "os.spawnve",
            "os.spawnvp",
            "os.spawnvpe",
            "os.startfile",
            "os.execv",
            "os.execve",
            "os.execl",
            "os.execle",
            "os.execlp",
            "os.execlpe",
            "multiprocessing.Process",
            "multiprocessing.Pool",
            "concurrent.futures.ProcessPoolExecutor",
            "pty.spawn",
            "pty.fork",
            "pexpect.spawn",
        },
        "javascript": {
            "child_process.spawn",
            "child_process.spawnSync",
            "child_process.exec",
            "child_process.execSync",
            "child_process.execFile",
            "child_process.execFileSync",
            "child_process.fork",
            "node:child_process.spawn",
            "node:child_process.spawnSync",
            "node:child_process.exec",
            "node:child_process.execSync",
            "node:child_process.execFile",
            "node:child_process.execFileSync",
            "node:child_process.fork",
            "cluster.fork",
            "worker_threads.Worker",
        },
        "go": {
            "os/exec.Command",
            "os/exec.CommandContext",
            "os/exec.Cmd.Run",
            "os/exec.Cmd.Start",
            "os/exec.Cmd.Output",
            "os/exec.Cmd.CombinedOutput",
            "os.StartProcess",
            "os.FindProcess",
            "os.Process.Kill",
            "os.Process.Signal",
            "syscall.Exec",
            "syscall.ForkExec",
            "syscall.StartProcess",
            "golang.org/x/sys/unix.Exec",
            "golang.org/x/sys/unix.ForkExec",
        },
    },
    "time_io": {
        "python": {
            "time.sleep",
            "time.monotonic",
            "time.perf_counter",
            "asyncio.sleep",
            "threading.Timer",
            "signal.alarm",
            "signal.setitimer",
        },
        "javascript": {
            "setTimeout",
            "setInterval",
            "setImmediate",
            "timers.setTimeout",
            "timers.setInterval",
            "timers.setImmediate",
            "timers/promises.setTimeout",
            "timers/promises.setImmediate",
            "scheduler.wait",
        },
        "go": {
            "time.Sleep",
            "time.After",
            "time.AfterFunc",
            "time.NewTimer",
            "time.NewTicker",
            "time.Tick",
        },
    },
    "randomness": {
        "python": {
            "random.random",
            "random.randint",
            "random.randrange",
            "random.choice",
            "random.choices",
            "random.sample",
            "random.shuffle",
            "random.uniform",
            "random.gauss",
            "random.getrandbits",
            "random.SystemRandom",
            "secrets.choice",
            "secrets.randbelow",
            "secrets.randbits",
            "secrets.token_bytes",
            "secrets.token_hex",
            "secrets.token_urlsafe",
            "os.urandom",
            "uuid.uuid1",
            "uuid.uuid3",
            "uuid.uuid4",
            "uuid.uuid5",
            "uuid.uuid6",
            "uuid.uuid7",
            "uuid.uuid8",
            "numpy.random.random",
            "numpy.random.rand",
            "numpy.random.randint",
            "numpy.random.choice",
            "numpy.random.default_rng",
        },
        "javascript": {
            "Math.random",
            "crypto.randomBytes",
            "crypto.randomInt",
            "crypto.randomUUID",
            "crypto.randomFill",
            "crypto.randomFillSync",
            "crypto.webcrypto.getRandomValues",
            "crypto.webcrypto.randomUUID",
            "globalThis.crypto.getRandomValues",
            "globalThis.crypto.randomUUID",
        },
        "go": {
            "math/rand.Int",
            "math/rand.Int31",
            "math/rand.Int31n",
            "math/rand.Int63",
            "math/rand.Int63n",
            "math/rand.Intn",
            "math/rand.Float32",
            "math/rand.Float64",
            "math/rand.Read",
            "math/rand/v2.Int",
            "math/rand/v2.Int64",
            "math/rand/v2.Uint",
            "math/rand/v2.Uint64",
            "math/rand/v2.Float32",
            "math/rand/v2.Float64",
            "crypto/rand.Read",
            "crypto/rand.Reader",
            "github.com/google/uuid.New",
            "github.com/google/uuid.NewString",
            "github.com/gofrs/uuid.New",
            "github.com/gofrs/uuid.NewV4",
        },
    },
}
